### ISSUE TITLE
getstore_pdbid

### ISSUE THREAD

**Issue by autolife** [demianriccardi/p5-HackaMol#27]
If you download a lot of pdb by the method, the website(pdb.org) will refuse your request.
the website will think downloading pdb by the robot not human.

one solvtion:
try mojo or LWP, disguise a browser.

**Comment by demianriccardi** [comment]
Thanks @autolife !

**Comment by dmr3** [comment]
The correct approach will be to use FTP downloads

**Comment by demianriccardi** [comment]
see HackaMol::Roles::RcsbRole

tests welcome!
