### ISSUE TITLE
Does HackaMol can parse out the solution of x-ray pdb? 

### ISSUE THREAD

**Issue by autolife** [demianriccardi/p5-HackaMol#28]
Does HackaMol can parse out the solution of x-ray pdb? 
for example ,give an pdb id,it will tell us what techology (X-RAY or NMR) and resolution ratio?

**Comment by demianriccardi** [comment]
The parser in HackaMol currently does not.  I have some old code that carves up the header and pulls out all sorts of information.  My plan is to work on this again in an extension HackaMol::X::PDB (or maybe name it HackaMol::X::RCSB).  My hopes for the extension is to support more metadata and handle symmetry operations and other file formats like pdbml.

**Comment by demianriccardi** [comment]
a cif parser has been added that parses fields such as method.  see the ReadPdbxRole.pm
