### ISSUE TITLE
Make the PDB download seamless

### ISSUE THREAD

**Issue by demianriccardi** [demianriccardi/p5-HackaMol#3]
Currently, a PDB will be downloaded only if it doesn't exist in the current directory.
1. Add a directory where PDBs can be stored.  If you want to work with a database of 1000 pdbs, HackaMol, should make that easy to set up in a persistent way. If a requested pdb doesn't exist, download it.  Since the database can include a ton of files, you could use the first two letters of the pdbid as a layer to the files.
2. Dream: use JSON to store the molecular object.  Time it out.  The trouble with this approach is the potential loss of information, that which isn't parsed from the file.

**Comment by demianriccardi** [comment]
first step:  added the method pdbid_mol which takes the PDB ID as an argument (e.g. 2cba), retrieves it from the pdb.org (unless it exists), loads it, and returns a molecule object.

**Comment by zmughal** [comment]
[URI::Fetch](http://p3rl.org/URI::Fetch) could help here. It includes the ability to cache URIs. Or if that is too high-level, work with [CHI](http://p3rl.org/CHI)'s File driver.

**Comment by demianriccardi** [comment]
Thanks for this suggestion, @zmughal!  It looks like a promising lead.
