### ISSUE TITLE
Wish: tied DCDs for easy analysis

### ISSUE THREAD

**Issue by demianriccardi** [demianriccardi/p5-HackaMol#46]
see Bio3d, mdtraj, etc...

**Comment by dmr3** [comment]
seems to be outside the scope of HackaMol.  HackaMol is a flexible, reliable tool to hack up and format nasty data.  However, such implementations would take way too much effort, especially considering there are awesome tools already.  Use bio3d, mdanalysis, mdtraj... or others for analysis for well-formatted trajectories!
