### ISSUE TITLE
adjust api for printing

### ISSUE THREAD

**Issue by dmr3** [demianriccardi/p5-HackaMol#48]
currently, print_pdb, xyz, etc. will either print to the screen or to a file handle.  A better approach would be to return a string (or lines or an iterator) that the user can decide where the output should go.  

a string could then be used for easy clones (not really clone, but gens of similar objects) via reading in strings.

Perhaps adding the new method would be a good start: 

````
form_string('pdb', [xyz .. etc])
````

**Comment by demianriccardi** [comment]
done

````
print $group->pdb_string
# easy 'cloning'
my $new_group = $bldr->read_string_mol( $group->string_pdb, 'pdb');
